baseURL = "https://minamikawada.github.io"
languageCode = "ja"
title = "My New Hugo Site"
hugo-themes = "hugo-identity-theme"
contentDir = "post"
disableKinds = ["RSS", "sitemap" ]
publishDir = "docs"
[taxonomies]
tag = "tags"


